# Generated by Django 5.1 on 2024-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
